# Generated by Django 2.2.12 on 2020-04-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='NAICSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='NAICS Code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='NAICS Title')),
            ],
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opportunity.Contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='naics_codes',
            field=models.ManyToManyField(blank=True, to='opportunity.NAICSCode', verbose_name='NAICS Code'),
        ),
    ]
