# Generated by Django 2.2.12 on 2020-04-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_auto_20200410_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitylisting',
            name='department',
        ),
    ]
