# Generated by Django 2.2.12 on 2020-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_remove_opportunitylisting_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitylisting',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
    ]
