# Generated by Django 2.2.12 on 2020-04-10 18:00

from django.db import migrations, models
import django.db.models.deletion
import opportunity.storage


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_auto_20200410_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIGPCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='NIGP Code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='NIGP Title')),
            ],
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='pre_submission_meeting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pre-Offer Conference/Pre-Submittal Meeting'),
        ),
        migrations.AlterField(
            model_name='opportunitylisting',
            name='naics_codes',
            field=models.ManyToManyField(blank=True, to='opportunity.NAICSCode', verbose_name='NAICS Codes'),
        ),
        migrations.CreateModel(
            name='ListingAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(storage=opportunity.storage.OverwriteStorage(), upload_to='uploads/%Y/%m/%d/', verbose_name='Attachment')),
                ('opportunitylisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.OpportunityListing', verbose_name='Opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='nigp_codes',
            field=models.ManyToManyField(blank=True, to='opportunity.NIGPCode', verbose_name='NIGP Codes'),
        ),
    ]
