# Generated by Django 2.2.12 on 2020-04-10 18:05

from django.db import migrations, models
import opportunity.storage


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_auto_20200410_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingattachment',
            name='attachment',
            field=models.FileField(max_length=500, storage=opportunity.storage.OverwriteStorage(), upload_to='uploads/%Y/%m/%d/', verbose_name='Attachment'),
        ),
    ]
