# Generated by Django 2.2.12 on 2020-04-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0007_auto_20200413_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitylisting',
            name='cities',
            field=models.ManyToManyField(blank=True, to='opportunity.City'),
        ),
        migrations.AlterField(
            model_name='opportunitylisting',
            name='product_service_categories',
            field=models.ManyToManyField(blank=True, to='opportunity.ProductServiceCategory', verbose_name='Product and Service Categories'),
        ),
        migrations.AlterField(
            model_name='opportunitylisting',
            name='shipto_service_locations',
            field=models.ManyToManyField(blank=True, to='opportunity.ShiptoServiceLocation', verbose_name='Ship-to or Service Locations'),
        ),
        migrations.AlterField(
            model_name='opportunitylisting',
            name='states',
            field=models.ManyToManyField(blank=True, to='opportunity.State'),
        ),
    ]
