# Generated by Django 2.2.12 on 2020-04-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_auto_20200413_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='State'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
