# Generated by Django 2.2.12 on 2020-04-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0011_auto_20200416_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitylisting',
            old_name='opprtunity_amount',
            new_name='opportunity_amount',
        ),
    ]
