# Generated by Django 2.2.12 on 2020-09-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0012_auto_20200420_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSCCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='PSC Code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='PSC Title')),
            ],
        ),
        migrations.AddField(
            model_name='buyerlisting',
            name='agency_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Agency Type'),
        ),
        migrations.AddField(
            model_name='buyerlisting',
            name='buyer_website_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Buyer Website ID'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='opportunity_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Opportunity Type'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='set_aside_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Set Aside Type'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='solicitation_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Solicitation Number'),
        ),
        migrations.CreateModel(
            name='OpportunityContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('contact_website_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Website ID')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opportunity.Contact')),
                ('opportunitylisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.OpportunityListing')),
            ],
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='Contacts', through='opportunity.OpportunityContact', to='opportunity.Contact'),
        ),
        migrations.AddField(
            model_name='opportunitylisting',
            name='psc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opportunity.PSCCode', verbose_name='PSC Category'),
        ),
    ]
