# Generated by Django 2.2.12 on 2020-09-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0013_auto_20200923_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitylisting',
            name='contract_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract Date'),
        ),
    ]
