# Generated by Django 2.2.12 on 2020-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0014_opportunitylisting_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingattachment',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Attachment Name'),
        ),
        migrations.AlterField(
            model_name='listingattachment',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Attachment'),
        ),
    ]
