# Generated by Django 2.2.12 on 2020-09-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0015_auto_20200925_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingattachment',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Attachment URL'),
        ),
    ]
