# Generated by Django 2.2.12 on 2020-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_listingattachment_attachment_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productservicecategory',
            old_name='category_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='opportunitylisting',
            name='contract_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract Start Date'),
        ),
    ]
