# Generated by Django 2.2.12 on 2020-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0017_auto_20200928_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservicecategory',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PSC Code'),
        ),
    ]
