# Generated by Django 2.2.12 on 2020-10-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0020_delete_psccode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamGovPSCCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='SAM.GOV PSC Code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='SAM.GOV PSC Title')),
            ],
        ),
        migrations.CreateModel(
            name='SetAsideCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Set Aside Code')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Set Aside Title')),
            ],
        ),
    ]
