# Generated by Django 2.2.12 on 2020-10-29 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0023_auto_20201029_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteOpportunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunitylisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.OpportunityListing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'opportunitylisting')},
            },
        ),
    ]
