# Generated by Django 2.2.12 on 2020-10-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0024_favoriteopportunities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingattachment',
            name='opportunitylisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingattachments', to='opportunity.OpportunityListing', verbose_name='Opportunity'),
        ),
    ]
