# Generated by Django 2.2.12 on 2021-02-23 12:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0026_userfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitylisting',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='opportunitylisting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='opportunity_search__6a6e69_gin'),
        ),
    ]
