# Generated by Django 2.2.12 on 2021-02-23 12:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0027_auto_20210223_1243'),
    ]

    migration = '''
            CREATE TRIGGER search_vector_update BEFORE INSERT OR UPDATE
            ON opportunity_opportunitylisting FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', title, posting_summary);

            -- Force triggers to run and populate the text_search column.
            UPDATE opportunity_opportunitylisting set ID = ID;
        '''

    reverse_migration = '''
            DROP TRIGGER search_vector_update ON opportunity_opportunitylisting;
        '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
