# Generated by Django 2.2.16 on 2021-02-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0028_create_text_search_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitylisting',
            name='is_deadline_ongoing',
            field=models.BooleanField(default=False, verbose_name='Is Deadline Ongoing?'),
        ),
    ]
